---
title: "Learning steers the ontogeny of an efficient hunting sequence in zebrafish larvae"
description: An executable documents to compement the eLife publication R Markdown
authors:
  - givenNames:
      - Konstantinos 
    familyNames:
      - Lagogiannis
    type: Person
  - givenNames:
      - Giovanni 
    familyNames:
      - Diana
    type: Person
  - givenNames:
      - Martin 
    familyNames:
      - Meyer
    type: Person
date: "03/11/2020"
output: html_document
---

# Results

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


library(tools)
library(RColorBrewer);
library("MASS");
library(extrafont) ##For F
library(mvtnorm)
library(boot) ## BootStrapping

library(ggplot2) ##install.packages("ggplot2")
library(ggExtra)##  install.packages("ggExtra") ##devtools::install_github("daattali/ggExtra").
library(cowplot)
library(ggpubr) ##install.packages("ggpubr")


source("config_lib.R")
setEnvFileLocations("HOME") #OFFICE,#LAPTOP HOME

source("DataLabelling/labelHuntEvents_lib.r")
source("Stats/stat_InformationTheoryAndCorrelations_bootstrap_lib.r")


datTrackedEventsRegister <- readRDS( paste(strDataExportDir,"/setn_huntEventsTrackAnalysis_Register_ToValidate.rds",sep="") ) ## THis is the Processed Register File On 
#lMotionBoutDat <- readRDS(paste(strDataExportDir,"/huntEpisodeAnalysis_MotionBoutData_SetC.rds",sep="") ) #Processed Registry on which we add )
#lEyeMotionDat <- readRDS(file=paste(strDataExportDir,"/huntEpisodeAnalysis_EyeMotionData_SetC",".rds",sep="")) #
lFirstBoutPoints <- readRDS(file=paste(strDataExportDir,"/huntEpisodeAnalysis_FirstBoutData_wCapFrame_Validated.rds",sep="")) ##Original :huntEpisodeAnalysis_FirstBoutData_Validated

#### Plot Raw Capture Data Indicating Low/High Speed Clustering for each
### Load Pre Calc RJAgs Model Results
##   stat_CaptSpeedVsDistance_RJags.RData ##stat_CaptSpeedCluster_RJags.RData
load(file =paste(strDataExportDir,"stat_CaptSpeedVsDistance_RJags.RData",sep=""))
##Calc Model Covariance
ntail <- 1500
fastClusterCovarSamples<-list()
fastClusterCovarSamples$LF <-tail(draw_LF$rho[2,,],ntail)
fastClusterCovarSamples$NF <-tail(draw_NF$rho[2,,],ntail)
fastClusterCovarSamples$DF <-tail(draw_DF$rho[2,,],ntail)
fastClusterCovarSamples$LFvsDF <- tail(fastClusterCovarSamples$LF , ntail)- tail(fastClusterCovarSamples$DF,ntail)
fastClusterCovarSamples$LFvsNF <- tail(fastClusterCovarSamples$LF , ntail)- tail(fastClusterCovarSamples$NF,ntail)

#### LOAD Capture First-Last Bout hunting that include the cluster classification - (made in stat_CaptureSpeedVsDistanceToPrey)
datCapture_NL <- readRDS(file=paste(strDataExportDir,"/huntEpisodeAnalysis_FirstBoutData_wCapFrame_NL_2Dclustered.rds",sep="")) 
datCapture_LL <- readRDS(file=paste(strDataExportDir,"/huntEpisodeAnalysis_FirstBoutData_wCapFrame_LL_2Dclustered.rds",sep="")) 
datCapture_DL <- readRDS(file=paste(strDataExportDir,"/huntEpisodeAnalysis_FirstBoutData_wCapFrame_DL_2Dclustered.rds",sep="")) 

datHuntLabelledEventsSB <- getLabelledHuntEventsSet()
datFishSuccessRate <- getHuntSuccessPerFish(datHuntLabelledEventsSB)

### PREAMP DONE####
##################



```

```{r figure-2-huntrate auxiliary functions}

## Compare Model TO Data Using CDF ##
plotEventCountDistribution_cdf <- function(datHEventCount,drawHEvent,lcolour,lpch,lty,Plim,nplotSamples=100,newPlot = FALSE)
{
  XLim <- 80
  x <- seq(0,XLim,1)

  cdfD_N <- ecdf(datHEventCount[,2])

  plot(cdfD_N,col=lcolour,pch=lpch,xlab=NA,ylab=NA,main="",xlim=c(0,XLim),ylim=c(0,1),cex=cex,cex.axis=cex,cex.lab=cex,add=!newPlot)
  ##Construct CDF of Model by Sampling randomly from Model distribution for exp rate parameter
  for (c in 1:NROW(drawHEvent$q[1,1,])) {
    for (j in (NROW(drawHEvent$q[,,c])-nplotSamples):NROW(drawHEvent$q[,,c]) )
    {
      cdfM <- dnbinom(x,size=drawHEvent$r[,j,c],prob=  drawHEvent$q[,j,c]  )##1-exp(-q*x) ##ecdf(  dexp( x, q  ) )
      lines(x,cumsum(cdfM),col=lcolour,lty=lty) #add=TRUE,
    }
  }
  plot(cdfD_N,col=colourP[4],pch=lpch,xlab=NA,ylab=NA,main="",xlim=c(0,XLim),ylim=c(0,1),cex=cex,cex.axis=cex,cex.lab=cex,add=TRUE)
  #axis(side = 4)
  #mtext(side = 4, line = 2.1, 'Counts')
  ### Draw Distribution oF Hunt Rates - 
  ## For Poisson- gamma mixture we recover Gamma Params from nbinomial as shape r>shape r and scale theta:(1-p)/p
  
  ##For the EXP Mixture with Poisson The Exp Rate was recovered as :
  ##(z= p/(1-p))
#  hist( (1-tail(drawHEvent$q[,,c],nplotSamples))/tail(drawHEvent$q[,,c],nplotSamples)  )
  
  
}


## Plot the Histogram, Empirical Density And Regressor Fit For A group Showing DENSITY VS Histogram #
plotEventCountDistribution_hist <- function(datHEventCount,drawHEvent,lcolour,HLim,nplotSamples)
{
  XLim <- 15
  x <- seq(0,Plim,0.1)
  N <- nplotSamples
  pBW <-1.2
  
  
  densHEventS <-density(datHEventCount[,2],bw=pBW)   
  histHEvent <- hist(datHEventCount[,2],breaks=seq(0,Plim,1),plot=FALSE)
  
  YLim <- 0.25 ##range(densHEventS$y)[2]*1.05
  par(mar = c(5,5,2,5))
  
  plot(densHEventS$x, densHEventS$y,type='l',xlim=c(0,XLim),ylim=c(0,YLim*1.20),xlab=NA, ylab=NA,lty=2,lwd=4)
  for (c in 1:NROW(drawHEvent$q[1,1,])) 
    for (r in (NROW(drawHEvent$q[,,c])-N):NROW(drawHEvent$q[,,c]))
      lines(x,dexp(x,rate=drawHEvent$q[,r,c] ),type="l",pch=16,cex=0.4,xlim=c(0,HLim),col=lcolour) 
  
  par(new=T)

  plot(histHEvent$breaks[1:NROW(histHEvent$counts)],histHEvent$counts, cex=1.1,ylab=NA,xlab=NA,axes=F,
       xlim=c(0.0,XLim),ylim=c(0,30 ) ,lwd=2,pch=21,col="#000000CC")
  
  axis(side = 4)
  mtext(side = 4,cex=cex, line = 2.1, 'Counts')
  mtext(side = 2,cex=cex, line = 2.1, 'P(s)')
  
}

## Plots The Spontaneous and Invoked Hunt Rates, Inferred via the gamma given by the -ve binomial
plotGammaHuntRates <- function(x,HEventHuntGammaShape,HEventHuntGammaRate,lcolour,plotsamples,lineType=1,bnewPlot=FALSE)
{
  schain <- 1:3
  if (bnewPlot)
    plot(x,(dgamma(x,shape=HEventHuntGammaShape[1,1],rate=HEventHuntGammaRate[1,1]) ),main="",xlab=NA,ylab=NA,
       xlim=c(0,15),ylim=c(0,0.5),col=lcolour,type="l",lwd=1, lty=lineType)

  for (c in schain)
  {
    for (i in 1:plotsamples)
    {
      lines(x, ( dgamma(x,shape=HEventHuntGammaShape[i,c],rate=HEventHuntGammaRate[i,c]) ) ,col=lcolour[1],lwd=1, lty=lineType)
      #lines(x,dgamma(x,rate=HEventHuntGammaShape[i,c],HEventHuntGammaRate[i,c]),col=lcolour[2],lwd=3,lty=3)
    }
  }
}
  

## Box Plot Assist To Connect Individual Hunt Event Counts Between Empty (Spontaneous) and Live Test Conditions (Evoked) 
## For Each Larva Experiment
plotConnectedEventCounts <- function(datHuntStat,vDat,strCondTags)
{
  
  ### Plot Connected Larva Event Counts - To Show Individual Behaviour In Spontaneous Vs Evoked Activity
  for (gIdx in seq(1,NROW(strCondTags),2)  ) ##Iterated Through LF DF And NF Groups
  {
    gE <- strCondTags[gIdx] ##Empty Condution
    gL <- strCondTags[gIdx+1] ##With ROtifers Test Condition 
    vRegL <- datHuntStat[,"vIDLookupTable"][[gL]]
    vRegE <- datHuntStat[,"vIDLookupTable"][[gE]]
    
    ## Fix Missing LarvaID: REMOVE FActor Field / Set NAs Which Are really ID 5
    vRegL[,"larvaID"] <- as.numeric(vRegL[,"larvaID"])
    vRegE[,"larvaID"] <- as.numeric(vRegE[,"larvaID"])
    vRegL[is.na(vRegL$larvaID),"larvaID"] <- 5 
    vRegE[is.na(vRegE$larvaID),"larvaID"] <- 5
    
    ## Drop Factors To Skip Errors 
    vRegL[,"dataSetID"] <- as.numeric(vRegL[,"dataSetID"])
    vRegE[,"dataSetID"] <- as.numeric(vRegE[,"dataSetID"])
    
    datSetID <- levels(vIDTable[[gE]]$dataSetID) #[ vIDTable[[gE]]$dataSetID[  vIDTable[[gE]]$larvaID == vIDTable[[gL]]$larvaID &
    #vIDTable[[gE]]$dataSetID == vIDTable[[gL]]$dataSetID] ]
    for (k in 1:NROW(vRegE) )
    {
      e <- vRegE[k,]
      
      ptSrc  <- vDat[[gE]][which(names(vDat[[gE]]) == e$expID) ]##Get Idx for Event Count from Specificed Experiment, and retrieve Event Count At Empty 
      ##Find the Live Test for this Larva, Via the Larva ID dataset ID combination
      LivePairExp <-(vRegL[vRegL$dataSetID == e$dataSetID & vRegL$larvaID == e$larvaID,])
      if (NROW(LivePairExp) == 0)
        next() ##Skip If Matched LiveTest Larva Is not Found
      
      message(e$expID)
      
      ptDest <- vDat[[gL]][which(names(vDat[[gL]]) %in% LivePairExp$expID) ]
      
      
      ##Plot The Lines Connect Each Empty Tested Larva With Itself In THe Live Fed Conditions 
      #Do not Plot NA connecting line
      idxSrc  <- match(gE,strCondTags) ##Bar Center Idx for Each Condition E. Fed
      idxDest <- match(gL ,strCondTags)           
      
      points(idxSrc,log10(ptSrc+1),pch=1,
             col=colourP[4],cex=1 )
      for (pIDest in ptDest) ##Sometimes there are Multiple Live Tests for an Empty One
        points(idxDest,log10(pIDest+1),pch=1, col=colourP[4],cex=1 )
      
      segments(gIdx,log10(ptSrc+1),gIdx+1,log10(ptDest+1) ,col=colourP[4])
      
      
    }##For Each Experiment
    
  } ## Go Through Pairs Of Conditions ##
}##End Of Function ConnectEventPoints

  
fromchain=1000

```

```{r fig2A_statComparePoissonHuntRates}

#nLL1=read.table("Stats/mcmc/testLL.dat")$Freq
#nNL1=read.table("Stats/mcmc/testNL.dat")$Freq
#nDL1=read.table("Stats/mcmc/testDL.dat")$Freq
## Load PreCalc Draws From Model ?? ##
load(file =paste(strDataExportDir,"stat_HuntRateInPreyRange_nbinomRJags.RData",sep=""))

############ LOAD EVENTS LIst and Fix ####
## Warning Set Includes Repeated Test For some LF fish - One In Different Food Density
## Merged2 Contains the Fixed, Remerged EventID 0 files, so event Counts appear for all larvae recorded.
#strProcDataFileName <- "setn15-HuntEvents-SB-Updated-Merged3"  ##Load the merged Frames
message(paste(" Loading Hunt Event List to Analyse... "))
#load(file=paste(strDatDir,"/LabelledSet/",strProcDataFileName,".RData",sep="" )) ##Save With Dataset Idx Identifier
datHuntLabelledEventsSBMerged_fixed <- getLabelledHuntEventsSet() # readRDS(file=paste(strDatDir,"/LabelledSet/",strProcDataFileName,".rds",sep="" ))


#---Filter Moved into   getLabelledHuntEventsSet() #Remove Dublicates - Choose Labels - Duration Needs To be > 5ms
  # datHuntLabelledEventsSBMerged_filtered <- datHuntLabelledEventsSBMerged [
  #                 with(datHuntLabelledEventsSBMerged, ( convertToScoreLabel(huntScore) != "Not_HuntMode/Delete" &
  #                                                                  convertToScoreLabel(huntScore) != "Duplicate/Overlapping" &
  #                                                                   (endFrame - startFrame) > 200 ) |  ## limit min event dur to 500ms
  #                                                                        eventID == 0), ] ## Add the 0 Event, In Case Larva Produced No Events
  ##These Are Double/2nd Trials on LL, or Simply LL unpaired to any LE (Was checking Rates)
  #AutoSet420fps_14-12-17_WTNotFed2RotiR_297_003.mp4
   vxCludeExpID <- c(4421,4611,4541,4351,4481,4501,4411)
   vWeirdDataSetID <- c(11,17,18,19) ##These Dataset Have a total N  Exp Less than 4*2*3=24
  # ##Check For Missing Exp Less than 24 
  # 
  # datHuntLabelledEventsSBMerged_fixed <- datHuntLabelledEventsSBMerged_filtered[!is.na(datHuntLabelledEventsSBMerged_filtered$groupID) & 
  #                                                                                 !(datHuntLabelledEventsSBMerged_filtered$expID %in% vxCludeExpID),]
for (dID in vWeirdDataSetID )
  print(NROW(unique(datHuntLabelledEventsSBMerged_fixed[datHuntLabelledEventsSBMerged_fixed$dataSetID ==  dID ,]$expID)))

################# # ## # # 


## Get Summarized Hunt Results Per Larva ####
datHuntStat <- makeHuntStat(datHuntLabelledEventsSBMerged_fixed)
datFishSuccessRate <- getHuntSuccessPerFish(datHuntLabelledEventsSB_LIVE)
   
##CHECK POINT ## - Hunt Rates between data processors
##
## vHLarvaEventCount includes all events regardless of scored outcome or even if they attempted at target --
## vHLarvaCaptureEventCount includes the count of events that attempted Capture / Either Success or Failed.
##
message( sum(datFishSuccessRate[datFishSuccessRate$groupID == "LL",]$HuntEvents), " Vs ",sum(datHuntStat[,"vHLarvaEventCount"]$LL)  )
message( sum(datFishSuccessRate[datFishSuccessRate$groupID == "NL",]$HuntEvents), " Vs ",sum(datHuntStat[,"vHLarvaEventCount"]$NL)  )
message( sum(datFishSuccessRate[datFishSuccessRate$groupID == "DL",]$HuntEvents), " Vs ",sum(datHuntStat[,"vHLarvaEventCount"]$DL)  )
#stopifnot(sum(datFishSuccessRate[datFishSuccessRate$groupID == "LL",]$HuntEvents) == sum(datHuntStat[,"vHLarvaEventCount"]$LL))
#stopifnot(NROW(datFishSuccessRate[datFishSuccessRate$groupID == "LL",]$HuntEvents) == NROW(datHuntStat[,"vHLarvaEventCount"]$LL))

   
## Get Event Counts Within Range  - Along With Total Number of Hunting frames for each Larva##
## Added Larva ID to Check for Correlation Through Time of Day - Surrogate as LarvaID;s increased through the day of the experiment from 1-4
datHuntVsPreyLL <- cbind(PreyCount=datHuntStat[,"vHInitialPreyCount"]$LL ,HuntEvents= as.numeric(datHuntStat[,"vHLarvaEventCount"]$LL),Duration=as.numeric(datHuntStat[,"vHDurationPerLarva"]$LL ),vID=datHuntStat[,"vIDLookupTable"]$LL$larvaID )
datHuntVsPreyLL <- datHuntVsPreyLL[!is.na(datHuntVsPreyLL[,1]) ,]
datHuntVsPreyLE <- cbind(datHuntStat[,"vHInitialPreyCount"]$LE , as.numeric(datHuntStat[,"vHLarvaEventCount"]$LE),Duration=as.numeric(datHuntStat[,"vHDurationPerLarva"]$LE ),datHuntStat[,"vIDLookupTable"]$LE$larvaID  )
datHuntVsPreyLE <- datHuntVsPreyLE[!is.na(datHuntVsPreyLE[,1]) ,]



datHuntVsPreyNL <- cbind(datHuntStat[,"vHInitialPreyCount"]$NL , as.numeric(datHuntStat[,"vHLarvaEventCount"]$NL),as.numeric(datHuntStat[,"vHDurationPerLarva"]$NL),datHuntStat[,"vIDLookupTable"]$NL$larvaID )
datHuntVsPreyNL <- datHuntVsPreyNL[!is.na(datHuntVsPreyNL[,1]) ,]
datHuntVsPreyNE <- cbind(datHuntStat[,"vHInitialPreyCount"]$NE , as.numeric(datHuntStat[,"vHLarvaEventCount"]$NE),as.numeric(datHuntStat[,"vHDurationPerLarva"]$NE),datHuntStat[,"vIDLookupTable"]$NE$larvaID  )
datHuntVsPreyNE <- datHuntVsPreyNE[!is.na(datHuntVsPreyNE[,1]) ,]

datHuntVsPreyDL <- cbind(datHuntStat[,"vHInitialPreyCount"]$DL , as.numeric(datHuntStat[,"vHLarvaEventCount"]$DL),as.numeric(datHuntStat[,"vHDurationPerLarva"]$DL ),datHuntStat[,"vIDLookupTable"]$DL$larvaID  )
datHuntVsPreyDL <- datHuntVsPreyDL[!is.na(datHuntVsPreyDL[,1]),] ##Remove NA And High Fliers
datHuntVsPreyDE <- cbind(datHuntStat[,"vHInitialPreyCount"]$DE , as.numeric(datHuntStat[,"vHLarvaEventCount"]$DE),as.numeric(datHuntStat[,"vHDurationPerLarva"]$DE ),datHuntStat[,"vIDLookupTable"]$DE$larvaID  )
datHuntVsPreyDE <- datHuntVsPreyDE[!is.na(datHuntVsPreyDE[,1]),] ##Remove NA And High Fliers

### Cut And Examine The data Where There Are Between L and M rotifers Initially
preyCntRange <- c(0,1100)

datHuntVsPreyLL <- (datHuntVsPreyLL[datHuntVsPreyLL[,1] >= preyCntRange[1] & datHuntVsPreyLL[,1] <= preyCntRange[2], ])
datHuntVsPreyDL <- (datHuntVsPreyDL[datHuntVsPreyDL[,1] >= preyCntRange[1] & datHuntVsPreyDL[,1] <= preyCntRange[2], ])
datHuntVsPreyNL <- (datHuntVsPreyNL[datHuntVsPreyNL[,1] >= preyCntRange[1] & datHuntVsPreyNL[,1] <= preyCntRange[2], ])

message("Analysis includes nLL: ",NROW(datHuntVsPreyLL), " nDL:",NROW(datHuntVsPreyDL)," nNL:",NROW(datHuntVsPreyNL))

## Check Number of Hunt Events For A LarvaID 
vEventCount <- vector()
datHuntVsPreyC <- datHuntVsPreyDL ##Check Which Group
for (i in 1:4)
{
  vEventCount[i] <- ( sum(datHuntVsPreyC[ datHuntVsPreyC[,4] == i & !is.na(datHuntVsPreyC[,4]) ,2] ) )
}
print(vEventCount)


### Rum The Sampler ###
drawLL2 <- mcmc_drawEventCountModels(datHuntVsPreyLL,preyCntRange,"modelGroupEventRate.tmp")
drawNL2 <- mcmc_drawEventCountModels(datHuntVsPreyNL,preyCntRange,"modelGroupEventRate.tmp")
drawDL2 <- mcmc_drawEventCountModels(datHuntVsPreyDL,preyCntRange,"modelGroupEventRate.tmp")
drawLE2 <- mcmc_drawEventCountModels(datHuntVsPreyLE,preyCntRange,"modelGroupEventRate.tmp")
drawNE2 <- mcmc_drawEventCountModels(datHuntVsPreyNE,preyCntRange,"modelGroupEventRate.tmp")
drawDE2 <- mcmc_drawEventCountModels(datHuntVsPreyDE,preyCntRange,"modelGroupEventRate.tmp")

save(drawLL2,drawNL2,drawDL2,drawLE2,drawNE2,drawDE2,file =paste(strDataExportDir,"stat_HuntRateInPreyRange_nbinomRJags.RData",sep=""))



### Draw Distribution oF Hunt Rates - 
## for the exp draw (z= p/(1-p)) ## But it is the same for Rate Of Gamma Too / Or inverse for scale
plotsamples <- 200
schain <-1:3

### The Prob Of Success p from NegBinom translates to Gamma Rate p/(1-p), or scale: (1-p)/p
HEventHuntGammaRate_LE <-tail(drawLE2$q[,,schain],plotsamples)/(1-tail(drawLE2$q[,,schain],plotsamples));
HEventHuntGammaRate_LL <-tail(drawLL2$q[,,schain],plotsamples)/(1-tail(drawLL2$q[,,schain],plotsamples));
HEventHuntGammaRate_DE <- tail(drawDE2$q[,,schain],plotsamples)/(1-tail(drawDE2$q[,,schain],plotsamples));
HEventHuntGammaRate_DL <- (tail(drawDL2$q[,,schain],plotsamples)/(1-tail(drawDL2$q[,,schain],plotsamples)));      
HEventHuntGammaRate_NE <- (tail(drawNE2$q[,,schain],plotsamples)/(1-tail(drawNE2$q[,,schain],plotsamples)));
HEventHuntGammaRate_NL <- (tail(drawNL2$q[,,schain],plotsamples)/(1-tail(drawNL2$q[,,schain],plotsamples)));      
HEventHuntGammaShape_LE <- tail(drawLE2$r[,,schain],plotsamples);
HEventHuntGammaShape_LL <- tail(drawLL2$r[,,schain],plotsamples)
HEventHuntGammaShape_DE <- tail(drawDE2$r[,,schain],plotsamples);
HEventHuntGammaShape_DL <- tail(drawDL2$r[,,schain],plotsamples)
HEventHuntGammaShape_NE <- tail(drawNE2$r[,,schain],plotsamples);
HEventHuntGammaShape_NL <- tail(drawNL2$r[,,schain],plotsamples)

## Calculate Hunt Rates ###
pBW = 0.5
densHPoissonRate_LL <- density( HEventHuntGammaShape_LL*1/HEventHuntGammaRate_LL,bw=pBW)
densHPoissonRate_LE <- density( HEventHuntGammaShape_LE*1/HEventHuntGammaRate_LE,bw=pBW)
densHPoissonRate_DE <- density( HEventHuntGammaShape_DE*1/HEventHuntGammaRate_DE,bw=pBW)
densHPoissonRate_DL <- density( HEventHuntGammaShape_DL*1/HEventHuntGammaRate_DL,bw=pBW)
densHPoissonRate_NE <- density( HEventHuntGammaShape_NE*1/HEventHuntGammaRate_NE,bw=pBW)
densHPoissonRate_NL <- density( HEventHuntGammaShape_NL*1/HEventHuntGammaRate_NL,bw=pBW)

##Mean SEM ##
muHuntRate_NL <- mean(HEventHuntGammaShape_NL*1/HEventHuntGammaRate_NL)
muHuntRate_LL <- mean(HEventHuntGammaShape_LL*1/HEventHuntGammaRate_LL)
muHuntRate_DL <- mean(HEventHuntGammaShape_DL*1/HEventHuntGammaRate_DL)

muHuntRate_NE <- mean(HEventHuntGammaShape_NE*1/HEventHuntGammaRate_NE)
muHuntRate_LE <- mean(HEventHuntGammaShape_LE*1/HEventHuntGammaRate_LE)
muHuntRate_DE <- mean(HEventHuntGammaShape_DE*1/HEventHuntGammaRate_DE)


semHuntRate_NL <- sd(HEventHuntGammaShape_NL*1/HEventHuntGammaRate_NL)/sqrt(NROW(HEventHuntGammaRate_NL)*NCOL(HEventHuntGammaRate_NL))
semHuntRate_LL <- sd(HEventHuntGammaShape_LL*1/HEventHuntGammaRate_LL)/sqrt(NROW(HEventHuntGammaRate_LL)*NCOL(HEventHuntGammaRate_LL))
semHuntRate_DL <- sd(HEventHuntGammaShape_DL*1/HEventHuntGammaRate_DL)/sqrt(NROW(HEventHuntGammaRate_DL)*NCOL(HEventHuntGammaRate_DL))


Plim <- max(range(datHuntVsPreyLL[,2])[2],range(datHuntVsPreyDL[,2])[2],range(datHuntVsPreyNL[,2])[2])
x <- seq(0.01,Plim,0.05)

#### HUNT EVENT PER LARVA PLOT #####
## Comprehensive Plot On Number of Hunt Events
#pdf(file= paste(strPlotExportPath,"/stat/fig2A_statComparePoissonHuntRates.pdf",sep=""),width = 14,height = 7)
  ##Now Plot Infered Distributions
  ##Show Alignment with Empirical Distribution of HuntEvent Numbers
  ## Number of Hunt Events Per Larva
  outer = FALSE
  line = 1 ## SubFig Label Params
  lineAxis = 3.2
  cex = 1.4
  adj  = 2.5
  padj <- -7.5
  las <- 1
  
  layout(matrix(c(1,1,2,2,3,3,4,4,4,5,5,5), 2,6, byrow = TRUE))
  ##Margin: (Bottom,Left,Top,Right )
  par(mar = c(4.0,4.75,1,1))
  
  #lineTypeL[1] <- 1
  plotEventCountDistribution_cdf(datHuntVsPreyNE,drawNE2,colourHE[1],pchL[1],lineTypeL[2],Plim,plotsamples,newPlot=TRUE )
  plotEventCountDistribution_cdf(datHuntVsPreyNL,drawNL2,colourHL[1],pchL[3],lineTypeL[2],Plim,plotsamples,newPlot=FALSE )
  legend("bottomright",legend = c(  expression (),
                                    bquote(NF["s"] ~ 'Data #' ~ .(NROW(datHuntVsPreyNE))  )
                                   ,bquote(NF["s"] ~"Model " ), 
                                   bquote(NF["e"] ~ 'Data #' ~ .(NROW(datHuntVsPreyNL)) )
                                   ,bquote( NF["e"] ~ "Model " ) ), 
         col=c(colourP[4], colourLegE[1],colourP[4],colourLegL[1]), pch=c(pchL[1],NA,pchL[3],NA),lty=c(NA,1),lwd=2,cex=cex,bg="white" )
  mtext("A",at="topleft",outer=outer,side=2,col="black",font=2,las=las,line=line,padj=padj,adj=adj,cex.main=cex,cex=cex)
  mtext(side = 1,cex=cex, line = lineAxis, "Hunt events / 10 min ")
  mtext(side = 2,cex=cex, line = lineAxis, " Cumulative function ")
  
  
  plotEventCountDistribution_cdf(datHuntVsPreyLE,drawLE2,colourHE[2],pchL[1],lineTypeL[2],Plim,plotsamples,newPlot=TRUE )
  plotEventCountDistribution_cdf(datHuntVsPreyLL,drawLL2,colourHL[2],pchL[3],lineTypeL[2],Plim,plotsamples,newPlot=FALSE )
  legend("bottomright",legend = c(  expression (),
                                    bquote(LF["s"] ~ 'Data #' ~ .(NROW(datHuntVsPreyLE))  )
                                    ,bquote(LF["s"] ~"Model " ), 
                                    bquote(LF["e"] ~ 'Data #' ~ .(NROW(datHuntVsPreyLL)) )
                                    ,bquote( LF["e"] ~ "Model " ) ), 
        col=c(colourP[4], colourLegE[2],colourP[4],colourLegL[2]), pch=c(pchL[1],NA,pchL[3],NA),lty=c(NA,1),lwd=2,cex=cex,bg="white" )
  mtext("B",at="topleft",outer=outer,side=2,col="black",font=2,las=las,line=line,padj=padj,adj=adj,cex.main=cex,cex=cex)
  mtext(side = 1,cex=cex, line = lineAxis, "Hunt events / 10 min ")
  mtext(side = 2,cex=cex, line = lineAxis, " Cumulative function ")
  
  
  plotEventCountDistribution_cdf(datHuntVsPreyDE,drawDE2,colourHE[3],pchL[1],lineTypeL[2],Plim,plotsamples,newPlot=TRUE  )
  plotEventCountDistribution_cdf(datHuntVsPreyDL,drawDL2,colourHL[3],pchL[3],lineTypeL[2],Plim,plotsamples,newPlot=FALSE  )
  legend("bottomright",legend = c(  expression (),
                                    bquote(DF["s"] ~ 'Data #' ~ .(NROW(datHuntVsPreyDE))  )
                                    ,bquote(DF["s"] ~"Model " ), 
                                    bquote(DF["e"] ~ 'Data #' ~ .(NROW(datHuntVsPreyDL)) )
                                    ,bquote( DF["e"] ~ "Model " ) ), 
         col=c(colourP[4], colourLegE[3],colourP[4],colourLegL[3]), pch=c(pchL[1],NA,pchL[3],NA),lty=c(NA,1),lwd=2,cex=cex,bg="white" )
  mtext(side = 1,cex=cex, line = lineAxis, "Hunt events / 10 min ")
  mtext(side = 2,cex=cex, line = lineAxis, " Cumulative function ")
  mtext("C",at="topleft",outer=outer,side=2,col="black",font=2,las=las,line=line,padj=padj,adj=adj,cex.main=cex,cex=cex)
  
  
  
  pchL <- c(1,2,0,16,17,15)
  ### Plot GAMMA Parameters Space ####
  #Xlim <- 50
  #plot(1/HEventHuntGammaRate_NE,HEventHuntGammaShape_NE,col=colourHL[1],ylim=c(0,3),xlim=c(0,Xlim),pch=pchL[1],xlab=NA,ylab=NA)
  #points(1/HEventHuntGammaRate_LE,HEventHuntGammaShape_LE,col=colourHL[2],ylim=c(0,3),xlim=c(0,Xlim),pch=pchL[2])
  #points(1/HEventHuntGammaRate_DE,HEventHuntGammaShape_DE,col=colourHL[3],ylim=c(0,3),xlim=c(0,Xlim),pch=pchL[3])
  #points(1/HEventHuntGammaRate_NL,HEventHuntGammaShape_NL,col=colourHL[1],ylim=c(0,3),xlim=c(0,Xlim),pch=pchL[4])
  #points(1/HEventHuntGammaRate_LL,HEventHuntGammaShape_LL,col=colourHL[2],ylim=c(0,3),xlim=c(0,Xlim),pch=pchL[5])
  #points(1/HEventHuntGammaRate_DL,HEventHuntGammaShape_DL,col=colourHL[3],ylim=c(0,3),xlim=c(0,Xlim),pch=pchL[6])
  #mtext(side = 1,cex=0.8, line = 2.2, expression(paste(Gamma, " scale (r)") ) )
  #mtext(side = 2,cex=0.8, line = 2.2, expression(paste(Gamma, " shape (k)") ) )
  #legend("topright",legend = strDataLabels,  #c(paste("NE" ), paste("LE"),paste("DE"), paste("NL"),paste("LL"),paste("DL")),
  #       col=c(colourHL[1],colourHL[2],colourHL[3],colourHL[1],colourHL[2],colourHL[3]) ,pch=pchL,cex=0.9,bg="white",ncol=2)
  #mtext("D",at="topleft",outer=outer,side=2,col="black",font=2,las=las,line=line,padj=padj,adj=adj,cex.main=cex)
  
  ###
  
  ## BoxPlot of Hunt Event Counts - 
  strCondTags <- c("NE","NL","LE","LL","DE","DL")
  xbarcenters <- boxplot(log10(datHuntVsPreyNE[,2]+1),log10(datHuntVsPreyNL[,2]+1),log10(datHuntVsPreyLE[,2]+1),log10(datHuntVsPreyLL[,2]+1),log10(datHuntVsPreyDE[,2]+1),log10(datHuntVsPreyDL[,2]+1),
          main=NA,notch=TRUE,col=colourD,names=strCondTags,ylim=c(0,2),axes = FALSE,cex=cex,cex.axis=cex  )
  mtext(side = 2,cex=cex, line =lineAxis, "Hunt events / 10 min. " ) #log(N+1)
  vIDTable    <- datHuntStat[,"vIDLookupTable"] ##vIDTable$DL <- vIDTable$DL[vIDTable$DL$expID!=3830,]
  vDat        <- (datHuntStat[,"vHLarvaEventCount"])
  
  axis(1,at<-axis(1,labels=NA),cex=cex,cex.axis=cex, labels=c( strDataLabels[1],strDataLabels[4],strDataLabels[2],strDataLabels[5],strDataLabels[3],strDataLabels[6] ))
  yticks <-axis(2,labels=NA)
  axis(2, at = yticks, labels =round(10^yticks)-1 , col.axis="black", las=2)
  #minor.tick() ##minor.tick(nx=4, ny=4, tick.ratio=4,x.args=NA) ## Can COnfuse to think scale is linear
  ## Connect Larvae From EMpty To LIve Test Condition #
  plotConnectedEventCounts(datHuntStat,vDat,strCondTags)
  mtext("D",at="topleft",outer=outer,side=2,col="black",font=2,las=las,line=line,padj=padj,adj=adj,cex.main=cex,cex=cex)
  
  
  ## Compare Distrib Of Poisson Rate Derived from Model  Params ##
  schain <- 1:3
  Ylim <- 3 
  pBW <- 0.001
  
  
  Ylim <- 0.7
  plot(densHPoissonRate_NL$x, densHPoissonRate_NL$y,type='l',lty=lineTypeL[2],col=colourLegL[1] ,lwd=4,ylab=NA,xlab=NA,xlim=c(0,25),ylim=c(0,Ylim),cex=cex,cex.axis=cex )
  lines(densHPoissonRate_LL$x, densHPoissonRate_LL$y,type='l',lty=lineTypeL[2],col=colourLegL[2],lwd=4,ylab=NA,xlab=NA)
  lines(densHPoissonRate_DL$x, densHPoissonRate_DL$y,type='l',lty=lineTypeL[2],col=colourLegL[3],lwd=4,ylab=NA,xlab=NA)
  
  lines(densHPoissonRate_NE$x, densHPoissonRate_NE$y,type='l',lty=lineTypeL[1],col=colourLegL[1],lwd=4,ylab=NA,xlab=NA)
  lines(densHPoissonRate_LE$x, densHPoissonRate_LE$y,type='l',lty=lineTypeL[1],col=colourLegL[2],lwd=4,ylab=NA,xlab=NA)
  lines(densHPoissonRate_DE$x, densHPoissonRate_DE$y,type='l',lty=lineTypeL[1],col=colourLegL[3],lwd=4,ylab=NA,xlab=NA)
  
  legend("topright",legend = c(paste("Spontaneous " ),paste("Evoked ")),seg.len=3.5
         , col=c(colourR[4], colourR[4]),lty=c(2,1),lwd=4,cex=cex,bg="white" )
  mtext(side = 1,cex=cex, line = lineAxis, expression(paste("Estimated hunt rate") )  ) #(",lambda," )
  mtext(side = 2,cex=cex, line = lineAxis, " Density function ")
  mtext("E",at="topleft",outer=outer,side=2,col="black",font=2,las=las,line=line,padj=padj,adj=adj,cex.main=cex,cex=cex)

#dev.off() 
```


```{r plot-aux-functions,include=FALSE}
###Used for drawing contour in ggplot -
## Draw the model fit above the cluster points
getFastClusterGrid <- function(drawMCMC)
{
  ### Add the cluster contours ###
  xran <- seq(0,0.8,0.05) ##Distance Grid
  yran <- seq(0,70,1) ##Speed Grid
  
  ##Example Code for PLotting Inferred Multivariate Cluster
  nsteps <- NROW(drawMCMC$mID[,,1][1,])
  mat_cov_fast <- rowMeans(drawMCMC$cov[2,,,(nsteps-1000):nsteps,1],dim=2) ##Average over samples
  
  mat_mu <- rowMeans(drawMCMC$mu[,,(nsteps-1000):nsteps,1],dim=2)
  #valGrid <- matrix( expand.grid(distance=xran,speed=yran),nrow=NROW(xran),ncol=NROW(yran) )
  valGrid <- expand.grid(distance=xran,speed=yran)
  #matrix(valGrid$distance,ncol=NROW(xran))
  cluster_z <- mvtnorm::dmvnorm(valGrid,mean=mat_mu[2,],sigma=mat_cov_fast )
  cluster_fast <- cbind(valGrid,cluster_z, factor(rep(16,NROW(valGrid) ),levels=c(1,16),labels=c("slow","fast")  ) )
  
  names(cluster_fast) <- c("DistanceToPrey", "CaptureSpeed", "Density","Cluster")
  
  return(cluster_fast)
}

###Used for drawing contour in ggplot
getSlowClusterGrid <- function(drawMCMC)
{
  ### Add the cluster contours ###
  xran <- seq(0,0.8,0.05) ##Distance Grid
  yran <- seq(0,70,1) ##Speed Grid
  
  ##Example Code for PLotting Inferred Multivariate Cluster
  nsteps <- NROW(drawMCMC$mID[,,1][1,])
  mat_cov_slow <- rowMeans(drawMCMC$cov[1,,,(nsteps-1000):nsteps,1],dim=2) ##Average over samples
  
  mat_mu <- rowMeans(drawMCMC$mu[,,(nsteps-1000):nsteps,1],dim=2)
  #valGrid <- matrix( expand.grid(distance=xran,speed=yran),nrow=NROW(xran),ncol=NROW(yran) )
  valGrid <- expand.grid(distance=xran,speed=yran)
  #matrix(valGrid$distance,ncol=NROW(xran))
  cluster_z <- mvtnorm::dmvnorm(valGrid,mean=mat_mu[1,],sigma=mat_cov_slow )
  cluster_slow <- cbind(valGrid,cluster_z, factor(rep(1,NROW(valGrid) ),levels=c(1,16),labels=c("slow","fast")  ) )
  
  names(cluster_slow) <- c("DistanceToPrey", "CaptureSpeed", "Density","Cluster")
  
  return(cluster_slow)
}

## Used for PCA 
standardizeHuntData <- function(datCapStat)
{
  within( datCapStat,{
    ###Assume split in High Low Values is around mean
    Efficiency_norm <- (Efficiency-mean(Efficiency))/sd(Efficiency) 
    HuntPower_norm    <- (HuntPower-mean(HuntPower)) /sd(HuntPower)
    CaptureSpeed_norm <-(CaptureSpeed-mean(CaptureSpeed))/sd(CaptureSpeed)
    DistSpeed_norm <- (DistanceToPrey*CaptureSpeed -mean(DistanceToPrey*CaptureSpeed))/sd(DistanceToPrey*CaptureSpeed)
    DistanceToPrey_norm <- (DistanceToPrey-mean(DistanceToPrey))/sd(DistanceToPrey)
    Undershoot_norm    <- (Undershoot-1)/sd(Undershoot)
    ##Use Centre As The Mean Of The Most Efficient Hunters
    TimeToHitPrey_norm <-   (FramesToHitPrey/G_APPROXFPS - mean(datCapStat[datCapStat$Efficiency >0.5,]$FramesToHitPrey/G_APPROXFPS) ) /sd(FramesToHitPrey/G_APPROXFPS)
    DistUnder_norm  <- (DistanceToPrey_norm*Undershoot_norm - mean(DistanceToPrey_norm*Undershoot_norm)) /sd(DistanceToPrey_norm*Undershoot_norm)   
    
  })
}

```


```{r fig3S1_stat_LarvalLengthsToHPI_Correlation,dev='png',cache=TRUE,include=FALSE}

### FIG 3 SUPP FIG HPI Corr-Larva Size

## Bootstrap correlation Analysis - Hunt Power Against Development/Nutrition Measured from Larval Std. Length
## Save To summary Stat Output - Used By generate figure 
datSuccessVsSize <- readRDS(file= paste(strDataExportDir,"/FishLengthVsHuntSuccess.rds",sep=""))
#\Loaded Structure datSuccessVsSize - Simplify Group Calls
datSuccessVsSize.NF <- datSuccessVsSize[datSuccessVsSize$groupID.y =="NL",]
datSuccessVsSize.LF <- datSuccessVsSize[datSuccessVsSize$groupID.y =="LL",]
datSuccessVsSize.DF <- datSuccessVsSize[datSuccessVsSize$groupID.y =="DL",]

#
datexp_SuccessVsSize<-datSuccessVsSize[,c(1,2,5,10,11,13,14)]
names(datexp_SuccessVsSize)[1] <- "expID"
names(datexp_SuccessVsSize)[2] <- "Length_mm"
datexp_SuccessVsSize[,2] <- datexp_SuccessVsSize[,2]*DIM_MMPERPX
write.csv(datexp_SuccessVsSize,file= paste(strDataExportDir,"/fig3S1_LengthVsHuntSuccess.csv",sep=""))

#\Loaded Structure datSuccessVsSize - Simplify Group Calls
dSuccessVsSize.NF <- datexp_SuccessVsSize[datexp_SuccessVsSize$groupID.y =="NL",]
dSuccessVsSize.LF <- datexp_SuccessVsSize[datexp_SuccessVsSize$groupID.y =="LL",]
dSuccessVsSize.DF <- datexp_SuccessVsSize[datexp_SuccessVsSize$groupID.y =="DL",]

XRange <- c(3.9,5)
YRange <- c(0,5)
pBw <- 0.05
stat_SizeVsHuntPower_NF <- bootStrap_stat(dSuccessVsSize.NF$Length_mm,dSuccessVsSize.NF$HuntPower,1000,XRange,YRange,"spearman")
stat_SizeVsHuntPower_LF <- bootStrap_stat(dSuccessVsSize.LF$Length_mm,dSuccessVsSize.LF$HuntPower,1000,XRange,YRange,"spearman")
stat_SizeVsHuntPower_DF <- bootStrap_stat(dSuccessVsSize.DF$Length_mm,dSuccessVsSize.DF$HuntPower,1000,XRange,YRange,"spearman")

#pdf(paste0(strPlotExportPath,"/stat/fig3S1_stat_LarvalLengthsToHPI_Correlation.pdf"),width=7,height=7,title="Correlation Larval size to Hunt Success (HPI) ",onefile = TRUE) #col=(as.integer(filtereddatAllFrames$expID))
    par(mar = c(3.9,4.7,1,1))
    
    plot(density(stat_SizeVsHuntPower_NF$corr,kernel="gaussian",bw=pBw),
         col=colourLegL[1],xlim=c(-0.5,0.5),lwd=3,lty=1,ylim=c(0,7),main=NA, xlab=NA,ylab=NA,cex=cex,cex.axis=cex) #expression(paste("slope ",gamma) ) )
    lines(density(stat_SizeVsHuntPower_LF$corr,kernel="gaussian",bw=pBw),col=colourLegL[2],lwd=3,lty=2)
    lines(density(stat_SizeVsHuntPower_DF$corr,kernel="gaussian",bw=pBw),col=colourLegL[3],lwd=3,lty=3)
    mtext(side = 1,cex=cex,cex.main=cex, line = lineXAxis, expression(paste("Correlation of hunt success (HPI) to larval length  ") ))
    mtext(side = 2,cex=cex,cex.main=cex, line = lineAxis, expression("Density function"))
    
    
    legend("topright",   legend=c( paste0("NF # ",  NROW(dSuccessVsSize.NF$expID) ),
                                   paste0("LF # " , NROW(dSuccessVsSize.LF$expID) ),
                                   paste0("DF # " , NROW(dSuccessVsSize.DF$expID) )
    ), ##paste(c("DL n=","LL n=","NL n="),c(NROW(lFirstBoutPoints[["DL"]][,1]),NROW(lFirstBoutPoints[["LL"]][,1]) ,NROW(lFirstBoutPoints[["NL"]][,1] ) ) )
    col=colourLegL,lty=c(1,2,3),lwd=3,cex=cex)
#dev.off() 
 
### Add Stat Test ###
message("LF Corr of Larval Size to Hunting Ability Is +ve")
t.test(stat_SizeVsHuntPower_LF$corr,alternative=c("greater"),paired=FALSE ) # "two.sided"
t.test(stat_SizeVsHuntPower_NF$corr,alternative=c("greater"),paired=FALSE ) # "two.sided"
t.test(stat_SizeVsHuntPower_DF$corr,alternative=c("greater"),paired=FALSE ) # "two.sided"



```


```{r fig4S1_FastClust_SpeedVsDistanceCovar,dev='png',fig.show='hold', out.width="50%", cache=TRUE,fig.cap='SpeedVsDistanceCovar',include=FALSE,echo=FALSE}
#### Fig 4 Supplemental - Covariance ####
strPlotName = paste(strPlotExportPath,"/stat/fig4S1_FastClust_SpeedVsDistanceCovar.pdf",sep="")

nSamples <- 10000 

outer = FALSE 
line = 1 ## SubFig Label Params
lineAxis = 2.4
lineXAxis = 3.0
cex = 1.0
adj  = 3.5
padj <- -16.0
las <- 1

stat_Cap_NF <- bootStrap_stat(datCapture_NL$DistanceToPrey,datCapture_NL$CaptureSpeed,nSamples,XRange,YRange)
stat_Cap_LF <- bootStrap_stat(datCapture_LL$DistanceToPrey,datCapture_LL$CaptureSpeed,nSamples,XRange,YRange)
stat_Cap_DF <- bootStrap_stat(datCapture_DL$DistanceToPrey,datCapture_DL$CaptureSpeed,nSamples,XRange,YRange)

stat_Cap_fast_NF <- bootStrap_stat(datCapture_NL[datCapture_NL$Cluster == "fast",]$DistanceToPrey,datCapture_NL[datCapture_NL$Cluster == "fast",]$CaptureSpeed,nSamples,XRange,YRange)
stat_Cap_fast_LF <- bootStrap_stat(datCapture_LL[datCapture_LL$Cluster == "fast",]$DistanceToPrey,datCapture_LL[datCapture_LL$Cluster == "fast",]$CaptureSpeed,nSamples,XRange,YRange)
stat_Cap_fast_DF <- bootStrap_stat(datCapture_DL[datCapture_DL$Cluster == "fast",]$DistanceToPrey,datCapture_DL[datCapture_DL$Cluster == "fast",]$CaptureSpeed,nSamples,XRange,YRange)

t.test(stat_SizeVsHuntPower_LF$corr,stat_Cap_fast_DF$corr,alternative=c("greater"),paired=FALSE ) # "two.sided"


## Fast CLuster Covariance
ntail <- 700

# Plot Fast_Cluster Speed Vs Distance Correlation - bootstraped Stat ##
dLLb_rho_fast <-density(fastClusterCovarSamples$LF,kernel="gaussian",bw=0.05)
dNLb_rho_fast <-density(fastClusterCovarSamples$NF,kernel="gaussian",bw=0.05)
dDLb_rho_fast <-density(fastClusterCovarSamples$DF,kernel="gaussian",bw=0.05)

#pdf(strPlotName,width=14,height=7,    title="Esimating Covariance of capture Speed-Distance in fast capture swims / A.Model Cluster B.Bootstrap Correlation    ",onefile = TRUE) #col=(as.integer(filtereddatAllFrames$expID))


  ##Margin: (Bottom,Left,Top,Right )
  par(mar = c(3.9,4.7,1,3))
  pBw <- 0.01
  ## Compare Bootstrap And Model COvariance - Fast Cluster 
  #layout(matrix(c(1,2),1,2, byrow = TRUE))
  
  
  plot(dNLb_rho_fast,col=colourLegL[1],xlim=c(-0.6,0.6),lwd=3,lty=1,ylim=c(0,10),
       main=NA, #"Density Inference of Turn-To-Prey Slope ",
       xlab=NA,ylab=NA,cex=cex,cex.axis=cex) #expression(paste("slope ",gamma) ) )
  lines(dLLb_rho_fast,col=colourLegL[2],lwd=3,lty=2)
  lines(dDLb_rho_fast,col=colourLegL[3],lwd=3,lty=3)
  mtext(side = 1,cex=cex, line = lineXAxis, expression("Model-estimated speed-distance correlation in fast cluster"  )) #
  mtext(side = 2,cex=cex, line = lineAxis, expression("Density function " ))
  
  #mtext(side = 3,cex=cex, line = lineTitle-3, expression("Capture distance and speed "  ))
  mtext("A",at="topleft",outer=outer,side=2,col="black",font=2,las=las,line=line,padj=padj,adj=adj,cex.main=cex,cex=cex)
  legend("topleft",         legend=c(  expression (),
                                        bquote(NF~ ''  ),
                                        bquote(LF ~ '' ),
                                        bquote(DF ~ '' )  ), ##paste(c("DL n=","LL n=","NL n="),c(NROW(lFirstBoutPoints[["DL"]][,1]),NROW(lFirstBoutPoints[["LL"]][,1]) ,NROW(lFirstBoutPoints[["NL"]][,1] ) ) )
         col=colourLegL,lty=c(1,2,3),lwd=3,cex=cex)
  ##Boot Strap
  plot(density(stat_Cap_fast_NF$corr,kernel="gaussian",bw=pBw),
       col=colourLegL[1],lwd=3,lty=1,xlim=c(-0.6,0.6),ylim=c(0,10),main=NA, xlab=NA,ylab=NA,cex=cex,cex.axis=cex) #expression(paste("slope ",gamma) ) )
  lines(density(stat_Cap_fast_LF$corr,kernel="gaussian",bw=pBw),col=colourLegL[2],lwd=3,lty=2)
  lines(density(stat_Cap_fast_DF$corr,kernel="gaussian",bw=pBw),col=colourLegL[3],lwd=3,lty=3)
  mtext(side = 1,cex=cex,cex.main=cex, line = lineXAxis, expression(paste("Bootstrapped speed-distance correlation in fast cluster") )) #in fast cluster
  mtext(side = 2,cex=cex,cex.main=cex, line = lineAxis, expression("Density function"))
  mtext("B",at="topleft",outer=outer,side=2,col="black",font=2,las=las,line=line,padj=padj,adj=adj,cex.main=cex,cex=cex)

#dev.off()
  ##Do Stat Associated With Plot
  
  message("Cluster Model Covariance - Probabilities")
  message("Prob Fast-cluster Cov NF > 0 : ", NROW(fastClusterCovarSamples$NF[fastClusterCovarSamples$NF>0])/length(fastClusterCovarSamples$NF) )
  message("Prob Fast-cluster Cov LF > 0 : ", NROW(fastClusterCovarSamples$LF[fastClusterCovarSamples$LF>0])/length(fastClusterCovarSamples$LF) )
  message("Prob Fast-cluster Cov DF > 0 : ", NROW(fastClusterCovarSamples$DF[fastClusterCovarSamples$DF>0])/length(fastClusterCovarSamples$DF) )
  message("Prob Fast-cluster Cov LF > DF : ", length(fastClusterCovarSamples$LFvsDF[fastClusterCovarSamples$LFvsDF>0]) / length(fastClusterCovarSamples$LFvsDF) )
  message("Prob Fast-cluster Cov LF > NF : ", length(fastClusterCovarSamples$LFvsNF[fastClusterCovarSamples$LFvsNF>0]) / length(fastClusterCovarSamples$LFvsNF) )
  
  message("BootStrapped Covariance")
  message("Estimate Prob of NF > 0 : ", NROW(stat_Cap_fast_NF[stat_Cap_fast_NF$corr>0,])/NROW(stat_Cap_fast_NF) )
  message("Estimate Prob of LF > 0 : ", NROW(stat_Cap_fast_LF[stat_Cap_fast_LF$corr>0,])/NROW(stat_Cap_fast_LF) )
  message("Estimate Prob of DF > 0 : ", NROW(stat_Cap_fast_DF[stat_Cap_fast_DF$corr>0,])/NROW(stat_Cap_fast_DF) )
  
  ## LF Has Higher Correlation than Control
  corrDiff_LFvsDF <- stat_Cap_fast_LF$corr - stat_Cap_fast_DF$corr
  corrDiff_LFvsNF <- stat_Cap_fast_LF$corr - stat_Cap_fast_NF$corr  
  message("Estimate Prob of LF > DF : ",NROW(corrDiff_LFvsDF[corrDiff_LFvsDF > 0])/NROW(corrDiff_LFvsDF) )
  message("Estimate Prob of LF > NF : ", NROW(corrDiff_LFvsNF[corrDiff_LFvsNF > 0])/NROW(corrDiff_LFvsNF) )
  
  
  test_FastClustCorr_NF <- t.test(stat_Cap_fast_NF$corr,stat_Cap_fast_NF$corr_suffled,alternative=c("greater"))
  test_FastClustCorr_LF <- t.test(stat_Cap_fast_LF$corr,stat_Cap_fast_LF$corr_suffled,alternative=c("greater"))
  test_FastClustCorr_DF <- t.test(stat_Cap_fast_DF$corr,stat_Cap_fast_DF$corr_suffled,alternative=c("greater"))
  test_FastClustCorr_LFvsDF <- t.test(stat_Cap_fast_LF$corr,stat_Cap_fast_DF$corr,alternative=c("greater"))
  test_FastClustCorr_LFvsNF <- t.test(stat_Cap_fast_LF$corr,stat_Cap_fast_NF$corr,alternative=c("greater"))
  message("T-test bootstrapped  Speed-Dist Corr  Fast Clust : NF corr is > 0 p=",test_FastClustCorr_NF$p.value )
  message("T-test bootstrapped  Speed-Dist  Corr Fast Clust : LF corr is > 0 p=",test_FastClustCorr_LF$p.value ) ##*** Significant
  message("T-test bootstrapped  Speed-Dist  Corr Fast Clust  : DF corr is > 0 p=",test_FastClustCorr_DF$p.value )
  message("T-test bootstrapped  Speed-Dist  Corr Fast Clust  : LF corr is > NF p=",test_FastClustCorr_LFvsNF$p.value )
  message("T-test bootstrapped  Speed-Dist  Corr Fast Clust  : LF corr is > DF p=",test_FastClustCorr_LFvsDF$p.value )

  ##LF Shows Higher Correlation Than DF
  t.test(stat_Cap_fast_LF$corr,stat_Cap_fast_DF$corr,alternative=c("greater"),paired=FALSE ) # "two.sided"
  ##LF Shows Higher Correlation Than NF
  t.test(stat_Cap_fast_LF$corr,stat_Cap_fast_NF$corr,alternative=c("greater"),paired=FALSE ) # "two.sided"
##END OF COVAR Fast Capture Swim
```  


```{r fig4_statbootstrap_correlation_SpeedVsDistance,dev='png',fig.show='hold', out.width="50%", cache=TRUE,fig.cap='Fig 4: SpeedVsDistanceCovar',include=FALSE,eval=TRUE,results=TRUE}
#### Covar All Captures Bootstrap ###
# Plot Speed Vs Distance Correlation - bootstraped Stat ## 
##Also Found in InfoTheoryBootstra[ ]
strPlotName = paste(strPlotExportPath,"/stat/fig4_statbootstrap_correlation_SpeedVsDistance.pdf",sep="")
#pdf(strPlotName,width=7,height=7,title="Correlations In Speed/Distance capture  variables",onefile = TRUE) #col=(as.integer(filtereddatAllFrames$expID))
  par(mar = c(3.9,4.7,1,1))
  
  plot(density(stat_Cap_NF$corr,kernel="gaussian",bw=pBw),
       col=colourLegL[1],xlim=c(0,1),lwd=3,lty=1,ylim=c(0,10),main=NA, xlab=NA,ylab=NA,cex=cex,cex.axis=cex) #expression(paste("slope ",gamma) ) )
  lines(density(stat_Cap_LF$corr,kernel="gaussian",bw=pBw),col=colourLegL[2],lwd=3,lty=2)
  lines(density(stat_Cap_DF$corr,kernel="gaussian",bw=pBw),col=colourLegL[3],lwd=3,lty=3)

  mtext(side = 1,cex=cex,cex.main=cex, line = lineXAxis, expression(paste("Correlation of capture speed to prey distance  ") ))
  mtext(side = 2,cex=cex,cex.main=cex, line = lineAxis, expression("Density function"))

#dev.off()

## Use BootStrap Library 
boot(cbind(DistanceToPrey=datCapture_NL$DistanceToPrey,CaptureSpeed=datCapture_NL$CaptureSpeed),R=1000,sim="ordinary",statistic=cor)

##Correlation Tests
##Note that Pearsons Assumes these are independent 
corrDistSpeed_NF <- cor.test(datCapture_NL$DistanceToPrey,datCapture_NL$CaptureSpeed,alternative="greater",method = "pearson")
corrDistSpeed_LF <-  cor.test(datCapture_LL$DistanceToPrey,datCapture_LL$CaptureSpeed,alternative="greater",method = "pearson")
corrDistSpeed_DF <- cor.test(datCapture_DL$DistanceToPrey,datCapture_DL$CaptureSpeed,alternative="greater",method = "pearson")
message("Pearson Corr Test: NF corr is > 0 p=",corrDistSpeed_NF$p.value )
message("Pearson Corr Test: LF corr is > 0 p=",corrDistSpeed_LF$p.value ) ##*** Significant
message("Pearson Corr Test: DF corr is > 0 p=",corrDistSpeed_DF$p.value )

## Do stat Associated With Plot
message("BootStrapped Covariance")
message("Estimate Prob of NF > 0 : ", NROW(stat_Cap_NF[stat_Cap_NF$corr>0,])/NROW(stat_Cap_NF) )
message("Estimate Prob of LF > 0 : ", NROW(stat_Cap_LF[stat_Cap_LF$corr>0,])/NROW(stat_Cap_LF) )
message("Estimate Prob of DF > 0 : ", NROW(stat_Cap_DF[stat_Cap_DF$corr>0,])/NROW(stat_Cap_DF) )

t_boot_speedVsDist_NF <- t.test( stat_Cap_NF$corr, stat_Cap_NF$corr_suffled, alternative=c("greater") )
t_boot_speedVsDist_LF <- t.test( stat_Cap_LF$corr, stat_Cap_LF$corr_suffled, alternative=c("greater") )
t_boot_speedVsDist_DF <- t.test( stat_Cap_DF$corr, stat_Cap_DF$corr_suffled, alternative=c("greater") )
message("T-test bootstrapped Corr Test: NF corr is > 0 p=",t_boot_speedVsDist_NF$p.value )
message("T-test bootstrapped  Corr Test: LF corr is > 0 p=",t_boot_speedVsDist_LF$p.value ) ##*** Significant
message("T-test bootstrapped  Corr Test: DF corr is > 0 p=",t_boot_speedVsDist_DF$p.value )

t.test( stat_Cap_LF$corr, alternative=c("greater") )


```